# Outpost 0.1.0
# Site: http://outpost.rocks
# Contribute: https://github.com/nickcernis/outpost-docker
# Maintainer: Nick Cernis <nick@cern.is>

version: '2'

services:
  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql/data

  outpost:
    depends_on:
      - db
    image: nickc/outpost
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./html:/var/www/html/

volumes:
  db_data: {}
